In [2]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from dateutil.parser import parse
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import  LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn import metrics
from sklearn.model_selection import cross_val_score
from sklearn.neighbors import KNeighborsClassifier
from datetime import datetime
import seaborn as sns

In [3]:
data1 = pd.read_csv('F:\Masters CS\kaggle\Kaggle Datasets Analysis\Lending Loan Dataset\LendingClub2012to2013.csv',header=1)

#see few rows and describe the dataset
data1.head()




C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\IPython\core\interactiveshell.py:2728: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


id   member_id  loan_amnt  funded_amnt  funded_amnt_inv        term  \
0  10129506  11981122.0    20800.0      20800.0          20800.0   36 months   
1  10159498   1319523.0    12000.0      12000.0          12000.0   36 months   
2  10129454  11981072.0    12000.0      12000.0          12000.0   36 months   
3  10139658  11991209.0    12000.0      12000.0          12000.0   36 months   
4  10127816  11979581.0    24000.0      24000.0          24000.0   36 months   

  int_rate  installment grade sub_grade            ...              \
0   13.53%       706.16     B        B5            ...               
1    6.62%       368.45     A        A2            ...               
2   10.99%       392.81     B        B2            ...               
3   13.53%       407.40     B        B5            ...               
4   13.53%       814.80     B        B5            ...               

  num_tl_90g_dpd_24m num_tl_op_past_12m pct_tl_nvr_dlq  percent_bc_gt_75  \
0                0.0                3.0           90.2              50.0   
1                0.0                2.0           95.5               0.0   
2                0.0                4.0          100.0               0.0   
3                0.0                2.0           81.2              33.3   
4                0.0                2.0          100.0              75.0   

  pub_rec_bankruptcies tax_liens tot_hi_cred_lim total_bal_ex_mort  \
0                  0.0       0.0         43100.0           23473.0   
1                  0.0       0.0        333044.0           42603.0   
2                  0.0       0.0         29700.0            7137.0   
3                  0.0       0.0         18130.0           13605.0   
4                  0.0       0.0        229072.0           61397.0   

  total_bc_limit total_il_high_credit_limit  
0        15000.0                        0.0  
1        52600.0                    42769.0  
2        18100.0                        0.0  
3         7000.0                    10030.0  
4        21500.0                    58847.0  

[5 rows x 115 columns]

In [4]:
data1.describe()


member_id      loan_amnt   funded_amnt  funded_amnt_inv  \
count  1.881810e+05  188181.000000  188181.00000    188181.000000   
mean   5.911942e+06   14354.139366   14351.61985     14339.617827   
std    3.343860e+06    8114.766207    8112.60861      8107.009785   
min    1.495120e+05    1000.000000    1000.00000       950.000000   
25%    2.216730e+06    8000.000000    8000.00000      8000.000000   
50%    6.047773e+06   12175.000000   12125.00000     12100.000000   
75%    8.721725e+06   20000.000000   20000.00000     19975.000000   
max    1.209697e+07   35000.000000   35000.00000     35000.000000   

         installment    annual_inc            dti    delinq_2yrs  \
count  188181.000000  1.881810e+05  188181.000000  188181.000000   
mean      443.736364  7.223328e+04      17.060171       0.239626   
std       242.646904  5.182459e+04       7.597634       0.703730   
min        21.620000  4.800000e+03       0.000000       0.000000   
25%       269.980000  4.500000e+04      11.340000       0.000000   
50%       398.210000  6.200000e+04      16.780000       0.000000   
75%       578.310000  8.700000e+04      22.580000       0.000000   
max      1408.130000  7.141778e+06      34.990000      29.000000   

       fico_range_low  fico_range_high             ...              \
count   188181.000000    188181.000000             ...               
mean       696.810119       700.810225             ...               
std         29.958302        29.958829             ...               
min        660.000000       664.000000             ...               
25%        675.000000       679.000000             ...               
50%        690.000000       694.000000             ...               
75%        710.000000       714.000000             ...               
max        845.000000       850.000000             ...               

       num_tl_90g_dpd_24m  num_tl_op_past_12m  pct_tl_nvr_dlq  \
count       160440.000000       160440.000000   160287.000000   
mean             0.063737            1.788014       95.399571   
std              0.367567            1.516775        7.391559   
min              0.000000            0.000000       15.000000   
25%              0.000000            1.000000       93.000000   
50%              0.000000            2.000000      100.000000   
75%              0.000000            3.000000      100.000000   
max             24.000000           25.000000      100.000000   

       percent_bc_gt_75  pub_rec_bankruptcies      tax_liens  tot_hi_cred_lim  \
count     179153.000000         188181.000000  188181.000000     1.604400e+05   
mean          53.558127              0.084785       0.014040     1.655453e+05   
std           34.148169              0.290168       0.241542     1.672533e+05   
min            0.000000              0.000000       0.000000     0.000000e+00   
25%           25.000000              0.000000       0.000000     4.479500e+04   
50%           50.000000              0.000000       0.000000     1.085000e+05   
75%           80.000000              0.000000       0.000000     2.437328e+05   
max          100.000000              8.000000      53.000000     9.999999e+06   

       total_bal_ex_mort  total_bc_limit  total_il_high_credit_limit  
count       1.806860e+05   180686.000000                1.604400e+05  
mean        4.288377e+04    20238.462072                3.438956e+04  
std         4.017789e+04    18883.558196                3.687963e+04  
min         0.000000e+00        0.000000                0.000000e+00  
25%         1.890425e+04     7800.000000                1.004950e+04  
50%         3.296300e+04    14700.000000                2.575150e+04  
75%         5.385975e+04    26500.000000                4.693525e+04  
max         2.644442e+06   522210.000000                1.214546e+06  

[8 rows x 90 columns]

In [5]:
#check the data types of each column
data1.dtypes

id                                 object
member_id                         float64
loan_amnt                         float64
funded_amnt                       float64
funded_amnt_inv                   float64
term                               object
int_rate                           object
installment                       float64
grade                              object
sub_grade                          object
emp_title                          object
emp_length                         object
home_ownership                     object
annual_inc                        float64
verification_status                object
issue_d                            object
loan_status                        object
pymnt_plan                         object
url                                object
desc                               object
purpose                            object
title                              object
zip_code                           object
addr_state                        

In [6]:
numeric_features = data1.select_dtypes(include=[np.number])
numeric_features.shape # 90 features are numeric

(188183, 90)

In [7]:
non_numeric_features = data1.select_dtypes(exclude=[np.number])
non_numeric_features.shape # 25 features are non numeric

(188183, 25)

In [8]:
non_numeric_features.dtypes #all the dtypes are in object form, look at the columns and convert them into
# string if it is a categorical variable and int,float if it is numeric

id                     object
term                   object
int_rate               object
grade                  object
sub_grade              object
emp_title              object
emp_length             object
home_ownership         object
verification_status    object
issue_d                object
loan_status            object
pymnt_plan             object
url                    object
desc                   object
purpose                object
title                  object
zip_code               object
addr_state             object
earliest_cr_line       object
revol_util             object
initial_list_status    object
last_pymnt_d           object
next_pymnt_d           object
last_credit_pull_d     object
application_type       object
dtype: object

In [9]:
non_numeric_list = non_numeric_features.columns
non_numeric_list

Index(['id', 'term', 'int_rate', 'grade', 'sub_grade', 'emp_title',
       'emp_length', 'home_ownership', 'verification_status', 'issue_d',
       'loan_status', 'pymnt_plan', 'url', 'desc', 'purpose', 'title',
       'zip_code', 'addr_state', 'earliest_cr_line', 'revol_util',
       'initial_list_status', 'last_pymnt_d', 'next_pymnt_d',
       'last_credit_pull_d', 'application_type'],
      dtype='object')

In [10]:
#see the unique values
data1.id.unique()

array([10129506, 10159498, 10129454, ..., '1058291',
       'Total amount funded in policy code 1: 2700702175',
       'Total amount funded in policy code 2: 81866225'], dtype=object)

In [11]:
#clean the data
data1.id[188181] = data1.id[188181].replace('Total amount funded in policy code 1: 2700702175','2700702175')
data1.id[188182] = data1.id[188182].replace('Total amount funded in policy code 2: 81866225','81866225')

C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


In [12]:
#convert id column into float64
data1.id = data1.id.astype(np.float64)
data1.id.dtypes

dtype('float64')

In [13]:
data1 = data1[data1.grade.notnull()]

In [14]:
data1.term.value_counts() #2 unique values
data1.term.isnull().sum()
data1.term = data1.term.fillna('0')
term= pd.get_dummies(data1.term,prefix='term')
data1 = pd.concat([data1,term],axis=1)
data1 = data1.drop('term',axis=1)
data1.int_rate.value_counts()

12.12%    9409
13.11%    8257
8.90%     7640
14.33%    7142
7.90%     6612
11.14%    6428
15.31%    5345
16.29%    5030
7.62%     4718
15.80%    4614
17.27%    4454
10.16%    4318
6.03%     4253
14.09%    4247
6.62%     3805
17.77%    3482
11.99%    3384
10.99%    3185
13.67%    2818
18.49%    2777
15.61%    2771
12.99%    2759
12.35%    2546
11.55%    2459
19.05%    2362
10.64%    2314
18.75%    2280
14.30%    2131
16.20%    2088
9.71%     2084
          ... 
22.45%     110
15.27%     107
15.96%     104
17.58%      97
22.78%      84
23.13%      73
18.64%      71
25.99%      63
19.91%      53
19.03%      53
26.06%      52
23.33%      47
19.42%      47
23.26%      46
20.30%      46
6.00%       41
24.20%      35
21.28%      31
20.89%      31
24.33%      21
21.67%      19
22.74%      12
22.06%      11
22.35%      11
24.52%       6
24.76%       6
24.11%       5
23.91%       3
23.52%       2
14.28%       1
Name: int_rate, Length: 145, dtype: int64

In [15]:

data1.grade.value_counts() # 7 unique values
data1.grade.isnull().sum()

0

In [16]:

data1.sub_grade.nunique() # 35
data1.emp_title.isnull().sum()
data1.emp_title = data1.emp_title.fillna('other')

In [17]:
#data cleaning
dic = {'years':'','year':'','10+ years':'10','< 1 year':'1','n/a':'0','10+':'10','< 1':'1'}

def empLength(x):
    for k,v in dic.items():
        x = x.replace(k,v)
    return x
   
data1.emp_length = data1.emp_length.astype(str)
data1.emp_length = data1.emp_length.apply(empLength)
data1.emp_length = data1.emp_length.apply(lambda x:  x.replace('s','') if 's' in x else x)
data1.emp_length.unique()
data1.emp_length.isnull().sum()
data1.emp_length = data1.emp_length.astype(np.float32)

In [18]:
data1.home_ownership.unique()
home_ownership= pd.get_dummies(data1.home_ownership,prefix='home_ownership')
data1 = pd.concat([data1,home_ownership],axis=1)
data1 = data1.drop('home_ownership',axis=1)

verification_status= pd.get_dummies(data1.verification_status,prefix='verification_status')
data1 = pd.concat([data1,verification_status],axis=1)
data1 = data1.drop('verification_status',axis=1)

data1.issue_d.isnull().sum()
data1.issue_d = data1.issue_d.apply(lambda x: parse(x))

data1.loan_status.unique()

data1.pymnt_plan.unique()

data1.title.nunique()

data1.revol_util.unique()

data1.initial_list_status.unique() 

data1.last_pymnt_d.isnull().sum()
data1.last_pymnt_d.nunique()
data1.last_pymnt_d = data1.last_pymnt_d.fillna(method='ffill')
data1.last_pymnt_d = data1.last_pymnt_d.apply(lambda x: parse(x))

data1.last_credit_pull_d.isnull().sum()
data1.last_credit_pull_d.nunique()
data1.last_credit_pull_d = data1.last_credit_pull_d.fillna(method='ffill')
data1.last_credit_pull_d = data1.last_credit_pull_d.apply(lambda x: parse(x))


y = data1.loc[:,['grade']].values

data1.int_rate = data1.int_rate.apply(lambda x: x.replace('%','') if '%' in x else x)
data1.int_rate = data1.int_rate.astype(np.float32)
data1.int_rate = data1.int_rate.apply(lambda x: x/100)

data1.loan_status.unique()

array(['Fully Paid', 'Current', 'Charged Off', 'Late (31-120 days)',
       'In Grace Period', 'Late (16-30 days)', 'Default'], dtype=object)

In [19]:
# predicting grade column
X = data1.loc[:,['loan_amnt','funded_amnt','funded_amnt_inv','int_rate']]



X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,random_state=42)


sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)


In [20]:
#Random Forest


model = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
model.fit(X_train,y_train)

C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:5: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='entropy',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [21]:
y_pred_grade = model.predict(X_test)
y_pred_grade

array(['A', 'A', 'E', ..., 'B', 'C', 'C'], dtype=object)

In [22]:
cm_random_grade = confusion_matrix(y_test,y_pred_grade)
cm_random_grade

array([[ 7184,     0,     0,     0,     0,     0,     0],
       [    1, 15761,     1,     1,     0,     0,     0],
       [    0,     1, 12517,    10,     0,     1,     0],
       [    2,     0,   144,  6697,     1,     0,     0],
       [    1,     1,     0,    28,  2933,    14,     0],
       [    0,     0,     0,     0,    45,  1397,    13],
       [    0,     0,     0,     0,     1,    39,   253]], dtype=int64)

In [24]:
#Naive Bayes

model_naive = GaussianNB()
model_naive.fit(X_train,y_train)
y_pred_naive_grade = model_naive.predict(X_test)
y_pred_naive_grade


C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['A', 'A', 'E', ..., 'B', 'C', 'C'],
      dtype='<U1')

In [25]:
cm_naive_grade= confusion_matrix(y_test,y_pred_naive_grade)
cm_naive_grade

array([[ 7184,     0,     0,     0,     0,     0,     0],
       [   36, 14867,   861,     0,     0,     0,     0],
       [    4,   723, 11539,   263,     0,     0,     0],
       [    3,     0,   261,  6323,   257,     0,     0],
       [    3,     0,     0,   199,  2596,   179,     0],
       [    0,     0,     0,     0,   140,  1222,    93],
       [    0,     0,     0,     0,     2,   128,   163]], dtype=int64)

In [26]:
#Decision Tree

model_DT = DecisionTreeClassifier()
model_DT.fit(X_train,y_train)

y_pred_DT_grade = model_DT.predict(X_test)
y_pred_DT_grade

array(['A', 'A', 'E', ..., 'B', 'C', 'C'], dtype=object)

In [27]:
cm_DT_grade = confusion_matrix(y_test,y_pred_DT_grade)
cm_DT_grade

array([[ 7184,     0,     0,     0,     0,     0,     0],
       [    0, 15762,     0,     2,     0,     0,     0],
       [    0,     0, 12519,     9,     0,     1,     0],
       [    0,     1,   137,  6706,     0,     0,     0],
       [    0,     1,     0,     2,  2974,     0,     0],
       [    0,     0,     0,     0,     2,  1446,     7],
       [    0,     0,     0,     0,     0,    26,   267]], dtype=int64)

In [28]:
#****************************************************************************************#
##############################    Predicting Loan status      ############################
#****************************************************************************************#
data1.isnull().sum()

cols = data1.select_dtypes(include=[np.number])

cols_drop_nan = cols.dropna(axis=1)

cols_filled_mean = cols.fillna(cols.mean())

In [30]:
#######################  visualization ################################
cols_drop_nan.columns

######plotting box plot#######
plt.figure()
plt.boxplot(cols_drop_nan.loan_amnt)
plt.ylabel('Loan Amount')
plt.title('Box Plot for Loan Amount')

Text(0.5,1,'Box Plot for Loan Amount')

In [31]:
a = cols[['total_pymnt','total_rec_prncp','total_rec_int','total_rec_late_fee']]
a.index = data1['last_pymnt_d']

a = a.cumsum()
a.plot.hist(stacked=True, bins=15,title='Histogram plot')
plt.figure()
a.iloc[5].plot()

In [32]:
#### plotting top five received interested rate#####
def top_five(df,n=5,column='total_rec_int'):
    return df.sort_index(by=column)[-n:]


b = top_five(data1)
b.index=b['last_pymnt_d']
b = b[['total_pymnt','total_rec_prncp','total_rec_int','total_rec_late_fee']]
b = b.cumsum()
b.plot(kind='barh',title='Top Five Received Interest Rate')


C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: by argument to sort_index is deprecated, pls use .sort_values(by=...)
  This is separate from the ipykernel package so we can avoid doing imports until


In [33]:
####Distribution###

cols_box1=cols_drop_nan[['loan_amnt','total_pymnt','total_rec_prncp','total_rec_int']]
cols_box2=cols_drop_nan[['int_rate','emp_length','dti']]
color = dict(boxes='DarkGreen', whiskers='DarkOrange',medians='DarkBlue', caps='Gray')

cols_box1.plot.box(color=color, sym='r+',title = 'Distribution of features_1')
cols_box2.plot.box(color=color, sym='r+',title = 'Distribution of features_2')

In [34]:
###### area plot ####
df_fico = cols_drop_nan[['fico_range_low','fico_range_high','last_fico_range_high','last_fico_range_low']]
df_fico.plot.area()


sns.set(style="whitegrid", color_codes=True)
sns.stripplot(x="loan_amnt", y="loan_status", data=data1)
sns.boxplot(x="loan_amnt", y="loan_status", hue='initial_list_status',data=data1)

In [35]:
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Logistic Regression @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
X_1 = data1.loc[:,cols_drop_nan.columns].values
y_lS = data1.loc[:,['loan_status']].values

X_train_2,X_test_2,y_train_2,y_test_2 = train_test_split(X_1,y_lS,test_size=0.25,random_state=42)

sc2 = StandardScaler()
X_train_2 = sc2.fit_transform(X_train_2)
X_test_2 = sc2.transform(X_test_2)

In [36]:
model_logistic = LogisticRegression()
model_logistic.fit(X_train_2,y_train_2)

y_pred_logistic = model_logistic.predict(X_test_2)


C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['Fully Paid', 'Fully Paid', 'Fully Paid', ..., 'Charged Off',
       'Charged Off', 'Charged Off'], dtype=object)

In [39]:
cm_logistic = confusion_matrix(y_test_2,y_pred_logistic)
cm_logistic
cm_logistic.shape

(7, 7)

In [40]:
report_logistic = metrics.classification_report(y_test_2,y_pred_logistic)
report_logistic

C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'                    precision    recall  f1-score   support\n\n       Charged Off       1.00      0.99      0.99      6833\n           Current       0.93      0.96      0.94      3945\n           Default       0.00      0.00      0.00         7\n        Fully Paid       0.99      1.00      1.00     35932\n   In Grace Period       0.00      0.00      0.00       105\n Late (16-30 days)       0.00      0.00      0.00        45\nLate (31-120 days)       0.23      0.03      0.06       179\n\n       avg / total       0.98      0.99      0.98     47046\n'

In [41]:
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Decision Tree @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#

model_Decision = DecisionTreeClassifier()
model_Decision.fit(X_train_2,y_train_2)

y_pred_Decision = model_Decision.predict(X_test_2)
y_pred_Decision

array(['Fully Paid', 'Fully Paid', 'Fully Paid', ..., 'Charged Off',
       'Charged Off', 'Charged Off'], dtype=object)

In [43]:
cm_Decision = confusion_matrix(y_test_2,y_pred_Decision)
cm_Decision


array([[ 6769,     0,     0,    64,     0,     0,     0],
       [    0,  3671,     1,     2,   115,    51,   105],
       [    0,     2,     2,     0,     1,     0,     2],
       [   43,     0,     0, 35889,     0,     0,     0],
       [    0,    82,     2,     0,     7,     6,     8],
       [    0,    39,     0,     0,     3,     1,     2],
       [    0,    86,     1,     0,    14,     6,    72]], dtype=int64)

In [44]:
report_Decision = metrics.classification_report(y_test_2,y_pred_Decision)
report_Decision

'                    precision    recall  f1-score   support\n\n       Charged Off       0.99      0.99      0.99      6833\n           Current       0.95      0.93      0.94      3945\n           Default       0.33      0.29      0.31         7\n        Fully Paid       1.00      1.00      1.00     35932\n   In Grace Period       0.05      0.07      0.06       105\n Late (16-30 days)       0.02      0.02      0.02        45\nLate (31-120 days)       0.38      0.40      0.39       179\n\n       avg / total       0.99      0.99      0.99     47046\n'

In [45]:
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ Naive Bayes @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#

model_naive = GaussianNB()
model_naive.fit(X_train_2,y_train_2)

y_pred_naive = model_naive.predict(X_test_2)
y_pred_naive

C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\utils\validation.py:547: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array(['Fully Paid', 'Fully Paid', 'Fully Paid', ..., 'Charged Off',
       'Late (16-30 days)', 'Charged Off'],
      dtype='<U18')

In [46]:
cm_naive = confusion_matrix(y_test_2,y_pred_naive)
cm_naive


array([[ 6143,     0,   426,     2,     0,   255,     7],
       [    0,    36,   183,     3,    16,  3676,    31],
       [    0,     0,     5,     0,     0,     2,     0],
       [  141,     1, 21415, 13009,     7,  1358,     1],
       [    0,     0,    12,     0,     0,    92,     1],
       [    0,     0,     6,     0,     0,    38,     1],
       [    0,     3,    27,     0,     1,   142,     6]], dtype=int64)

In [47]:
report_naive = metrics.classification_report(y_test_2,y_pred_naive)
report_naive

'                    precision    recall  f1-score   support\n\n       Charged Off       0.98      0.90      0.94      6833\n           Current       0.90      0.01      0.02      3945\n           Default       0.00      0.71      0.00         7\n        Fully Paid       1.00      0.36      0.53     35932\n   In Grace Period       0.00      0.00      0.00       105\n Late (16-30 days)       0.01      0.84      0.01        45\nLate (31-120 days)       0.13      0.03      0.05       179\n\n       avg / total       0.98      0.41      0.54     47046\n'

In [48]:
#@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@  KNN  @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#



model_KNN = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
model_KNN.fit(X_train_2,y_train_2)

y_pred_KNN = model_KNN.predict(X_test_2)
y_pred_KNN

C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\ipykernel_launcher.py:6: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  


array(['Fully Paid', 'Fully Paid', 'Fully Paid', ..., 'Fully Paid',
       'Charged Off', 'Charged Off'], dtype=object)

In [49]:
cm_KNN = confusion_matrix(y_test_2,y_pred_KNN)
cm_KNN

array([[ 5254,    16,     0,  1563,     0,     0,     0],
       [   20,  3590,     0,   320,     7,     0,     8],
       [    2,     0,     0,     5,     0,     0,     0],
       [  312,    33,     0, 35587,     0,     0,     0],
       [    0,    87,     0,    17,     0,     0,     1],
       [    0,    36,     0,     8,     0,     0,     1],
       [   14,   129,     0,    31,     0,     0,     5]], dtype=int64)

In [50]:
report_KNN = metrics.classification_report(y_test_2,y_pred_KNN)
report_KNN

C:\Users\rishi\Anaconda3\envs\tensorflow\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


'                    precision    recall  f1-score   support\n\n       Charged Off       0.94      0.77      0.85      6833\n           Current       0.92      0.91      0.92      3945\n           Default       0.00      0.00      0.00         7\n        Fully Paid       0.95      0.99      0.97     35932\n   In Grace Period       0.00      0.00      0.00       105\n Late (16-30 days)       0.00      0.00      0.00        45\nLate (31-120 days)       0.33      0.03      0.05       179\n\n       avg / total       0.94      0.94      0.94     47046\n'

In [51]:
#@@@@@@@@@@@@@@@@@@@@@@@@@@@ Apllying k-fold Cross Validation @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#
y_train_2 = y_train_2.reshape(141135,)
accuracies_Decision = cross_val_score(estimator = model_Decision, X = X_train_2, y = y_train_2, cv = 3,n_jobs=-1)
accuracies_Decision.mean()
accuracies_Decision.std()

0.0005132462530260621

In [52]:
accuracies_logistic = cross_val_score(estimator = model_logistic, X = X_train_2, y = y_train_2, cv = 3,n_jobs=-1)
accuracies_logistic.mean()
accuracies_logistic.std()

0.00056129138642199196

In [ ]:
accuracies_Naive = cross_val_score(estimator = model_naive, X = X_train_2, y = y_train_2, cv = 3,n_jobs=-1)
accuracies_Naive.mean()
accuracies_Naive.std()

0.067005427099474088

In [ ]:
accuracies_KNN= cross_val_score(estimator = model_KNN, X = X_train_2, y = y_train_2, cv = 3,n_jobs=-1)
accuracies_KNN.mean()
accuracies_KNN.std()
